/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    Auth: typeof import('./src/layouts/Auth.vue')['default']
    BlogCard: typeof import('./src/components/BlogCard.vue')['default']
    ChangePassword: typeof import('./src/views/auth/ChangePassword.vue')['default']
    CountdownTimer: typeof import('./src/components/base/CountdownTimer.vue')['default']
    Dashboard: typeof import('./src/layouts/Dashboard.vue')['default']
    DoctorsList: typeof import('./src/views/home/DoctorsList.vue')['default']
    ForgotPassword: typeof import('./src/views/auth/ForgotPassword.vue')['default']
    History: typeof import('./src/views/dashboard/History.vue')['default']
    Home: typeof import('./src/layouts/Home.vue')['default']
    Landing: typeof import('./src/views/home/Landing.vue')['default']
    Login: typeof import('./src/views/auth/Login.vue')['default']
    Profile: typeof import('./src/views/dashboard/Profile.vue')['default']
    RecoveryPassword: typeof import('./src/views/auth/RecoveryPassword.vue')['default']
    Register: typeof import('./src/views/auth/Register.vue')['default']
    ResetPassword: typeof import('./src/views/auth/ResetPassword.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendCode: typeof import('./src/views/auth/SendCode.vue')['default']
    SendResetCode: typeof import('./src/views/auth/SendResetCode.vue')['default']
    SetNewPassword: typeof import('./src/views/auth/SetNewPassword.vue')['default']
    SetPassword: typeof import('./src/views/auth/SetPassword.vue')['default']
    SvgLoader: typeof import('./src/components/base/SvgLoader.vue')['default']
    TheButton: typeof import('./src/components/base/TheButton.vue')['default']
    TheCountdownTimer: typeof import('./src/components/base/TheCountdownTimer.vue')['default']
    TheInput: typeof import('./src/components/base/TheInput.vue')['default']
    TheNavbar: typeof import('./src/components/base/TheNavbar.vue')['default']
    TheSelect: typeof import('./src/components/base/TheSelect.vue')['default']
    TheSidebar: typeof import('./src/components/base/TheSidebar.vue')['default']
    VerifyCode: typeof import('./src/views/auth/VerifyCode.vue')['default']
    VerifyOTP: typeof import('./src/views/auth/VerifyOTP.vue')['default']
    VerifyResetCode: typeof import('./src/views/auth/VerifyResetCode.vue')['default']
  }
}
