/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    Auth: typeof import('./src/layouts/Auth.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    ChangePassword: typeof import('./src/views/auth/ChangePassword.vue')['default']
    Comments: typeof import('./src/components/Comments.vue')['default']
    Complaint: typeof import('./src/views/dashboard/Complaint.vue')['default']
    Dashboard: typeof import('./src/layouts/Dashboard.vue')['default']
    DoctoeDetails: typeof import('./src/views/home/DoctorDetails.vue')['default']
    DoctorCard: typeof import('./src/components/DoctorCard.vue')['default']
    DoctorDetails: typeof import('./src/views/home/DoctorDetails.vue')['default']
    DoctorsList: typeof import('./src/views/home/DoctorsList.vue')['default']
    Home: typeof import('./src/layouts/Home.vue')['default']
    InfoCard: typeof import('./src/components/InfoCard.vue')['default']
    Landing: typeof import('./src/views/home/Landing.vue')['default']
    Login: typeof import('./src/views/auth/Login.vue')['default']
    Notifications: typeof import('./src/views/dashboard/Notifications.vue')['default']
    Profile: typeof import('./src/views/dashboard/Profile.vue')['default']
    RecoveryPassword: typeof import('./src/views/auth/RecoveryPassword.vue')['default']
    Register: typeof import('./src/views/auth/Register.vue')['default']
    Reservations: typeof import('./src/views/dashboard/Reservations.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleTable: typeof import('./src/components/ScheduleTable.vue')['default']
    SvgLoader: typeof import('./src/components/base/SvgLoader.vue')['default']
    TheButton: typeof import('./src/components/base/TheButton.vue')['default']
    TheComment: typeof import('./src/components/TheComment.vue')['default']
    TheCountdownTimer: typeof import('./src/components/base/TheCountdownTimer.vue')['default']
    TheIcon: typeof import('./src/components/base/TheIcon.vue')['default']
    TheInput: typeof import('./src/components/base/TheInput.vue')['default']
    TheModal: typeof import('./src/components/base/TheModal.vue')['default']
    TheNavbar: typeof import('./src/components/base/TheNavbar.vue')['default']
    TheSectionTitle: typeof import('./src/components/base/TheSectionTitle.vue')['default']
    TheSelect: typeof import('./src/components/base/TheSelect.vue')['default']
    TheSidebar: typeof import('./src/components/base/TheSidebar.vue')['default']
    TheTable: typeof import('./src/components/base/TheTable.vue')['default']
    TheTitle: typeof import('./src/components/base/TheTitle.vue')['default']
    Transactions: typeof import('./src/views/dashboard/Transactions.vue')['default']
  }
}
