/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    Auth: typeof import('./src/layouts/Auth.vue')['default']
    BlogCard: typeof import('./src/components/BlogCard.vue')['default']
    ChangePassword: typeof import('./src/views/auth/ChangePassword.vue')['default']
    Dashboard: typeof import('./src/layouts/Dashboard.vue')['default']
    DoctorsList: typeof import('./src/views/dashboard/DoctorsList.vue')['default']
    History: typeof import('./src/views/dashboard/History.vue')['default']
    Home: typeof import('./src/layouts/Home.vue')['default']
    Landing: typeof import('./src/views/home/Landing.vue')['default']
    Login: typeof import('./src/views/auth/Login.vue')['default']
    Profile: typeof import('./src/views/dashboard/Profile.vue')['default']
    RecoveryPassword: typeof import('./src/views/auth/RecoveryPassword.vue')['default']
    Register: typeof import('./src/views/auth/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgLoader: typeof import('./src/components/base/SvgLoader.vue')['default']
    TheButton: typeof import('./src/components/base/TheButton.vue')['default']
    TheInput: typeof import('./src/components/base/TheInput.vue')['default']
    TheNavbar: typeof import('./src/components/base/TheNavbar.vue')['default']
    TheSidebar: typeof import('./src/components/base/TheSidebar.vue')['default']
  }
}
