# Generated by Django 6.0.2 on 2026-02-16 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_user_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reservation',
        ),
    ]
