# Generated by Django 6.0.2 on 2026-02-16 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_remove_comment_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('RESERVE', 'رزرو نوبت'), ('CANCEL', 'لغو نوبت')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, help_text='برای پزشک (اگر اعلان برای پزشک باشد)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='برای بیمار (اگر اعلان برای بیمار باشد)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_as_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='Core_notifi_user_id_d42b43_idx'), models.Index(fields=['doctor', 'created_at'], name='Core_notifi_doctor__adf4f5_idx')],
            },
        ),
    ]
