# Generated by Django 6.0.2 on 2026-02-16 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(choices=[('PAY', 'پرداخت'), ('REFUND', 'بازگشت وجه')], max_length=10, verbose_name='نوع تراکنش')),
                ('method', models.CharField(choices=[('BANK', 'درگاه بانکی'), ('WALLET', 'کیف پول')], max_length=10, verbose_name='روش پرداخت')),
                ('status', models.CharField(choices=[('SUCCESS', 'موفق'), ('FAILED', 'ناموفق'), ('PENDING', 'در انتظار')], default='SUCCESS', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تراکنش')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='Core.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
