# Generated by Django 6.0.2 on 2026-02-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_type',
            new_name='type',
        ),
    ]
