# Generated by Django 6.0.2 on 2026-02-20 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_alter_comment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='تخصص')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تخصص',
                'verbose_name_plural': 'تخصص\u200cها',
            },
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='field',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='Core.specialty', verbose_name='تخصص'),
        ),
    ]
