# Generated by Django 6.0.2 on 2026-02-20 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_alter_transaction_status_wallet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'verbose_name': 'دکتر', 'verbose_name_plural': 'دکتر\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'اعلان', 'verbose_name_plural': 'اعلان\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='passwordreset',
            options={'ordering': ['-created_when'], 'verbose_name': 'ریست پسورد', 'verbose_name_plural': 'ریست پسوردها'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'رزرو', 'verbose_name_plural': 'رزرو\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربر\u200cها'},
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='متن شکایت')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('REVIEWED', 'بررسی شده'), ('RESOLVED', 'حل شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'شکایت',
                'verbose_name_plural': 'شکایات',
                'ordering': ['-created_at'],
            },
        ),
    ]
