# Generated by Django 6.0.2 on 2026-02-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_alter_comment_options_alter_doctorprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام درگاه')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد درگاه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'درگاه پرداخت',
                'verbose_name_plural': 'درگاه\u200cهای پرداخت',
            },
        ),
        migrations.CreateModel(
            name='ReportProxy',
            fields=[
            ],
            options={
                'verbose_name': 'گزارش\u200cها',
                'verbose_name_plural': 'گزارش\u200cها و آمار',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Core.transaction',),
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'نوبت', 'verbose_name_plural': 'نوبت\u200cها'},
        ),
    ]
