# Generated by Django 6.0.2 on 2026-02-20 19:01

import Core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_paymentgateway_reportproxy_alter_reservation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان سند')),
                ('file', models.FileField(upload_to=Core.models.medical_record_upload_path, verbose_name='فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='Core.doctorprofile', verbose_name='پزشک')),
            ],
            options={
                'verbose_name': 'سند پزشکی',
                'verbose_name_plural': 'اسناد پزشکی',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
